### ISSUE TITLE
Is there a way to keep the server starting without getting a catalog?

### ISSUE THREAD

**Issue by toras9000** [Quiq/registry-ui#79]
In registry-ui v0.10.3, I think the server tries to get the catalog from the registry the moment it starts, and if it fails, the server stops working.  
Is there any way to make the server continue to start itself even if access to the registry fails at the moment of startup?  
The assumption is that the system will start with no data, expecting it to be acquired at the next acquisition timing.  

The above question was asked because we wanted to let the service continue to start up even if it was not yet ready to access the registry when we tried to start it up in the following order.  

1. Start registry.
2. Start token authentication server.
3. Start registry-ui
4. Start reverse proxy.

I rely on translation tools. I'm sorry if there is a strange sentence.

**Comment by roman-vynar** [comment]
Yes, it tries to get the catalog the moment it starts. It can't get it instantly so this runs in background. However, if it fails immediately because the registry is not available it fails to start completely.

It is possible to add a config option to not fail app/web server startup with unreachable registry and then try to do that as usual - refresh the catalog on interval.
